### ISSUE TITLE
"bin/buildout -c jenkins.cfg -n && bin/jenkins-test" gives "ImportError: No module named CMFPlacefulWorkflow"

### ISSUE THREAD

**Issue by idgserpro** [plone/buildout.jenkins#20]
I have jenkins.cfg in my package:

```
[buildout]
extends =
    buildout.cfg
    https://raw.github.com/plone/buildout.jenkins/master/jenkins.cfg

jenkins-test-eggs = collective.myproduct [test]

[code-analysis]
jenkins = True
```

When calling ```bin/buildout -c jenkins.cfg -n && bin/jenkins-test``` I get ```ImportError: No module named CMFPlacefulWorkflow```. Just running bin/test I don't have this problem. Here is the full traceback:

```
Running Products.PloneTestCase.layer.PloneSite tests:
  Set up Testing.ZopeTestCase.layer.ZopeLite in 0.428 seconds.
  Set up Products.PloneTestCase.layer.ZCML Traceback (most recent call last):
  File "/home/plone/.buildout/eggs/zope.testrunner-4.1.1-py2.7.egg/zope/testrunner/runner.py", line 380, in run_layer
    setup_layer(options, layer, setup_layers)
  File "/home/plone/.buildout/eggs/zope.testrunner-4.1.1-py2.7.egg/zope/testrunner/runner.py", line 667, in setup_layer
    setup_layer(options, base, setup_layers)
  File "/home/plone/.buildout/eggs/zope.testrunner-4.1.1-py2.7.egg/zope/testrunner/runner.py", line 672, in setup_layer
    layer.setUp()
  File "/home/plone/.buildout/eggs/Products.PloneTestCase-0.9.18-py2.7.egg/Products/PloneTestCase/layer.py", line 15, in setUp
    five.safe_load_site()
  File "/home/plone/.buildout/eggs/Products.PloneTestCase-0.9.18-py2.7.egg/Products/PloneTestCase/five.py", line 52, in safe_load_site
    zcml.load_site()
  File "/home/plone/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 649, in file
    include(context, name, package)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/home/plone/.pythonz/pythons/CPython-2.7.9/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/plone/.pythonz/pythons/CPython-2.7.9/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/plone/.pythonz/pythons/CPython-2.7.9/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/home/plone/.pythonz/pythons/CPython-2.7.9/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/plone/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/metaconfigure.py", line 46, in loadProducts
    xmlconfig.include(_context, zcml, package=product)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/home/plone/.pythonz/pythons/CPython-2.7.9/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/home/plone/.pythonz/pythons/CPython-2.7.9/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/home/plone/.pythonz/pythons/CPython-2.7.9/lib/python2.7/xml/sax/expatreader.py", line 210, in feed
    self._parser.Parse(data, isFinal)
  File "/home/plone/.pythonz/pythons/CPython-2.7.9/lib/python2.7/xml/sax/expatreader.py", line 352, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/home/plone/.buildout/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/home/plone/.buildout/eggs/z3c.autoinclude-0.3.5-py2.7.egg/z3c/autoinclude/zcml.py", line 101, in includePluginsDirective
    info = PluginFinder(dotted_name).includableInfo(zcml_to_look_for)
  File "/home/plone/.buildout/eggs/z3c.autoinclude-0.3.5-py2.7.egg/z3c/autoinclude/plugin.py", line 18, in includableInfo
    groups = zcml_to_include(plugin_dottedname, zcml_to_look_for)
  File "/home/plone/.buildout/eggs/z3c.autoinclude-0.3.5-py2.7.egg/z3c/autoinclude/plugin.py", line 36, in zcml_to_include
    filename = resource_filename(dotted_name, zcmlgroup)
  File "/home/plone/.buildout/eggs/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 1160, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "/home/plone/.buildout/eggs/setuptools-18.0.1-py2.7.egg/pkg_resources/__init__.py", line 435, in get_provider
    __import__(moduleOrReq)
  File "/home/plone/.buildout/eggs/plone.app.upgrade-1.3.10-py2.7.egg/plone/app/upgrade/__init__.py", line 132, in <module>
    from Products.CMFPlacefulWorkflow import interfaces
ZopeXMLConfigurationError: File "/home/plone/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Zope2/utilities/skel/etc/site.zcml", line 12.2-12.39
    ZopeXMLConfigurationError: File "/home/plone/.buildout/eggs/Products.CMFPlone-4.3.6-py2.7.egg/Products/CMFPlone/meta.zcml", line 42.4-46.10
    ImportError: No module named CMFPlacefulWorkflow
```

Adding **Products.CMFPlacefulWorkflow** to ```install_requires``` in my setup.py solves the issue, but I don't even use it in my collective.myproduct so I don't think it's the best approach.

Has anyone seen a problem like this one? Is this a jenkins problem or a problem with my setup?

**Comment by idgserpro** [comment]
This issue can be closed. The fix was made in plone.app.upgrade (and where this issue was supposed to be in the first place).
